export default class CurrencyUI {
    constructor() {
        //catch DOM elements 
        /*
        1. Search Section 
                فيها: 
                Country Select
                City Select
                Year Select
                Explore Button
         */

        this.popularCurrenciesGrid = document.querySelector(".popular-currencies-grid");
        this.currencyToCountry = {
            AED: "AE",
            AFN: "AF",
            ALL: "AL",
            AMD: "AM",
            ANG: "CW",
            AOA: "AO",
            ARS: "AR",
            AUD: "AU",
            AWG: "AW",
            AZN: "AZ",
            BAM: "BA",
            BBD: "BB",
            BDT: "BD",
            BGN: "BG",
            BHD: "BH",
            BIF: "BI",
            BMD: "BM",
            BND: "BN",
            BOB: "BO",
            BRL: "BR",
            BRX: "BR",
            BSD: "BS",
            BWP: "BW",
            BYN: "BY",
            BZD: "BZ",
            CAD: "CA",
            CDF: "CD",
            CHF: "CH",
            CLF: "CL",
            CLP: "CL",
            CNH: "CN",
            CNY: "CN",
            COP: "CO",
            COU: "CO",
            CRC: "CR",
            CUP: "CU",
            CVE: "CV",
            CZK: "CZ",
            DJF: "DJ",
            DKK: "DK",
            DOP: "DO",
            DZD: "DZ",
            EGP: "EG",
            ERN: "ER",
            ETB: "ET",
            EUR: "EU",
            FJD: "FJ",
            FKP: "FK",
            GBP: "GB",
            GEL: "GE",
            GHS: "GH",
            GIP: "GI",
            GMD: "GM",
            GNF: "GN",
            GTQ: "GT",
            GYD: "GY",
            HKD: "HK",
            HNL: "HN",
            HTG: "HT",
            HUF: "HU",
            HUX: "HU",
            IDR: "ID",
            ILS: "IL",
            INR: "IN",
            IQD: "IQ",
            IRR: "IR",
            ISK: "IS",
            JMD: "JM",
            JOD: "JO",
            JPY: "JP",
            KES: "KE",
            KGS: "KG",
            KHR: "KH",
            KMF: "KM",
            KPW: "KP",
            KRW: "KR",
            KWD: "KW",
            KYD: "KY",
            KZT: "KZ",
            LAK: "LA",
            LBP: "LB",
            LKR: "LK",
            LRD: "LR",
            LSL: "LS",
            LYD: "LY",
            MAD: "MA",
            MDL: "MD",
            MGA: "MG",
            MKD: "MK",
            MMK: "MM",
            MNT: "MN",
            MOP: "MO",
            MRU: "MR",
            MUR: "MU",
            MVR: "MV",
            MWK: "MW",
            MXN: "MX",
            MXV: "MX",
            MYR: "MY",
            MZN: "MZ",
            NAD: "NA",
            NGN: "NG",
            NIO: "NI",
            NOK: "NO",
            NPR: "NP",
            NZD: "NZ",
            OMR: "OM",
            PAB: "PA",
            PEN: "PE",
            PGK: "PG",
            PHP: "PH",
            PKR: "PK",
            PLN: "PL",
            PYG: "PY",
            QAR: "QA",
            RON: "RO",
            RSD: "RS",
            RUB: "RU",
            RWF: "RW",
            SAR: "SA",
            SBD: "SB",
            SCR: "SC",
            SDG: "SD",
            SEK: "SE",
            SGD: "SG",
            SHP: "SH",
            SLL: "SL",
            SOS: "SO",
            SRD: "SR",
            SSP: "SS",
            STN: "ST",
            SVC: "SV",
            SYP: "SY",
            SZL: "SZ",
            THB: "TH",
            TJS: "TJ",
            TMT: "TM",
            TND: "TN",
            TOP: "TO",
            TRY: "TR",
            TTD: "TT",
            TWD: "TW",
            TZS: "TZ",
            UAH: "UA",
            UGX: "UG",
            USD: "US",
            UYU: "UY",
            UZS: "UZ",
            VES: "VE",
            VND: "VN",
            VUV: "VU",
            WST: "WS",
            XAF: "CM",
            XCD: "AG",
            XDR: "UN",
            XOF: "SN",
            XPF: "PF",
            YER: "YE",
            ZAR: "ZA",
            ZMW: "ZM"
        };
        this.currencyNames = {
            AED: "United Arab Emirates Dirham",
            AFN: "Afghan Afghani",
            ALL: "Albanian Lek",
            AMD: "Armenian Dram",
            ANG: "Netherlands Antillean Guilder",
            AOA: "Angolan Kwanza",
            ARS: "Argentine Peso",
            AUD: "Australian Dollar",
            AWG: "Aruban Florin",
            AZN: "Azerbaijani Manat",
            BAM: "Bosnia-Herzegovina Convertible Mark",
            BBD: "Barbadian Dollar",
            BDT: "Bangladeshi Taka",
            BGN: "Bulgarian Lev",
            BHD: "Bahraini Dinar",
            BIF: "Burundian Franc",
            BMD: "Bermudian Dollar",
            BND: "Brunei Dollar",
            BOB: "Bolivian Boliviano",
            BRL: "Brazilian Real",
            BRX: "Brazilian Real Commercial",
            BSD: "Bahamian Dollar",
            BWP: "Botswana Pula",
            BYN: "Belarusian Ruble",
            BZD: "Belize Dollar",
            CAD: "Canadian Dollar",
            CDF: "Congolese Franc",
            CHF: "Swiss Franc",
            CLF: "Chilean Unit of Account (UF)",
            CLP: "Chilean Peso",
            CNH: "Chinese Yuan Offshore",
            CNY: "Chinese Yuan",
            COP: "Colombian Peso",
            COU: "Unidad de Valor Real",
            CRC: "Costa Rican Colón",
            CUP: "Cuban Peso",
            CVE: "Cape Verdean Escudo",
            CZK: "Czech Koruna",
            DJF: "Djiboutian Franc",
            DKK: "Danish Krone",
            DOP: "Dominican Peso",
            DZD: "Algerian Dinar",
            EGP: "Egyptian Pound",
            ERN: "Eritrean Nakfa",
            ETB: "Ethiopian Birr",
            EUR: "Euro",
            FJD: "Fijian Dollar",
            FKP: "Falkland Islands Pound",
            GBP: "British Pound Sterling",
            GEL: "Georgian Lari",
            GHS: "Ghanaian Cedi",
            GIP: "Gibraltar Pound",
            GMD: "Gambian Dalasi",
            GNF: "Guinean Franc",
            GTQ: "Guatemalan Quetzal",
            GYD: "Guyanese Dollar",
            HKD: "Hong Kong Dollar",
            HNL: "Honduran Lempira",
            HTG: "Haitian Gourde",
            HUF: "Hungarian Forint",
            HUX: "Hungarian Forint Commercial",
            IDR: "Indonesian Rupiah",
            ILS: "Israeli New Shekel",
            INR: "Indian Rupee",
            IQD: "Iraqi Dinar",
            IRR: "Iranian Rial",
            ISK: "Icelandic Króna",
            JMD: "Jamaican Dollar",
            JOD: "Jordanian Dinar",
            JPY: "Japanese Yen",
            KES: "Kenyan Shilling",
            KGS: "Kyrgyzstani Som",
            KHR: "Cambodian Riel",
            KMF: "Comorian Franc",
            KPW: "North Korean Won",
            KRW: "South Korean Won",
            KWD: "Kuwaiti Dinar",
            KYD: "Cayman Islands Dollar",
            KZT: "Kazakhstani Tenge",
            LAK: "Lao Kip",
            LBP: "Lebanese Pound",
            LKR: "Sri Lankan Rupee",
            LRD: "Liberian Dollar",
            LSL: "Lesotho Loti",
            LYD: "Libyan Dinar",
            MAD: "Moroccan Dirham",
            MDL: "Moldovan Leu",
            MGA: "Malagasy Ariary",
            MKD: "Macedonian Denar",
            MMK: "Myanmar Kyat",
            MNT: "Mongolian Tögrög",
            MOP: "Macanese Pataca",
            MRU: "Mauritanian Ouguiya",
            MUR: "Mauritian Rupee",
            MVR: "Maldivian Rufiyaa",
            MWK: "Malawian Kwacha",
            MXN: "Mexican Peso",
            MXV: "Mexican Investment Unit",
            MYR: "Malaysian Ringgit",
            MZN: "Mozambican Metical",
            NAD: "Namibian Dollar",
            NGN: "Nigerian Naira",
            NIO: "Nicaraguan Córdoba",
            NOK: "Norwegian Krone",
            NPR: "Nepalese Rupee",
            NZD: "New Zealand Dollar",
            OMR: "Omani Rial",
            PAB: "Panamanian Balboa",
            PEN: "Peruvian Sol",
            PGK: "Papua New Guinean Kina",
            PHP: "Philippine Peso",
            PKR: "Pakistani Rupee",
            PLN: "Polish Złoty",
            PYG: "Paraguayan Guaraní",
            QAR: "Qatari Riyal",
            RON: "Romanian Leu",
            RSD: "Serbian Dinar",
            RUB: "Russian Ruble",
            RWF: "Rwandan Franc",
            SAR: "Saudi Riyal",
            SBD: "Solomon Islands Dollar",
            SCR: "Seychellois Rupee",
            SDG: "Sudanese Pound",
            SEK: "Swedish Krona",
            SGD: "Singapore Dollar",
            SHP: "Saint Helena Pound",
            SLL: "Sierra Leonean Leone",
            SOS: "Somali Shilling",
            SRD: "Surinamese Dollar",
            SSP: "South Sudanese Pound",
            STN: "São Tomé and Príncipe Dobra",
            SVC: "Salvadoran Colón",
            SYP: "Syrian Pound",
            SZL: "Swazi Lilangeni",
            THB: "Thai Baht",
            TJS: "Tajikistani Somoni",
            TMT: "Turkmenistani Manat",
            TND: "Tunisian Dinar",
            TOP: "Tongan Paʻanga",
            TRY: "Turkish Lira",
            TTD: "Trinidad and Tobago Dollar",
            TWD: "New Taiwan Dollar",
            TZS: "Tanzanian Shilling",
            UAH: "Ukrainian Hryvnia",
            UGX: "Ugandan Shilling",
            USD: "United States Dollar",
            UYU: "Uruguayan Peso",
            UZS: "Uzbekistani Soʻm",
            VES: "Venezuelan Bolívar",
            VND: "Vietnamese Đồng",
            VUV: "Vanuatu Vatu",
            WST: "Samoan Tala",
            XAF: "Central African CFA Franc",
            XCD: "East Caribbean Dollar",
            XDR: "Special Drawing Rights",
            XOF: "West African CFA Franc",
            XPF: "CFP Franc",
            YER: "Yemeni Rial",
            ZAR: "South African Rand",
            ZMW: "Zambian Kwacha"
        };

    }

    renderLatestExchangesRates(exchangesObj) {
        let cartona = "";
        for (const [key, value] of Object.entries(exchangesObj)) {
            const countryName = this.currencyNames[key];
            const countryCode = this.currencyToCountry[key];
            const flagUrl = `https://flagcdn.com/48x36/${countryCode.toLowerCase()}.png`;
            cartona += `
              <div class="popular-currency-card">
                        <img src="${flagUrl}" alt="${key}" class="flag">
                        <div class="info">
                        <div class="code">${key}</div>
                        <div class="name">${countryName}</div>
                        </div>
                        <div class="rate">${value}</div>
              </div>`
        }

    }
}